# system variables
#NUMBER_OF_ROBOTS = 10
SQUAD_SIZE = 20
SQUAD_START = 100
SQUAD_END = SQUAD_START + SQUAD_SIZE
AUTO_BOT_SIZE = 5
COMM_SQUAD_SIZE = SQUAD_SIZE - AUTO_BOT_SIZE

# communication parameters
PORT = 5005 
SENDING_ATTEMPTS = 20
BC_IP = '192.168.178.255'

# protocol messages # TODO: define!
COMMAND_GO_IDLE = "GO_IDLE"
COMMAND_GO_AUTO = "GO_AUTO"
COMMAND_GO_COMM = "GO_COMM"
COMMAND_START_ALL = "START_ALL"
COMMAND_MODE = "mode"
COMMAND_SPEED = "speed"
COMMAND_INCREMENT = '+'
COMMAND_DECREMENT = '-'
VALUE_MODE_INIT = "init"
VALUE_MODE_IDLE = "idle"

# robots
SPEED_RUN = 75
SPEED_SLOW = 50
SPEED_WARN = 25
SPEED_STOP = 0
SPEED_CONTROL_MAX = 75
SPEED_CONTROL_MIN = 50
DIST_MIN = 20
DIST_MAX = 50
DIST_REF = DIST_MAX
WAIT_DIST = 0.1
WAIT_SEND = 0.00001
LED_OFF = 0
LED_ON = 1000
SENDING_ATTEMPTS = 5
KP = 0.4



