# system variables
#NUMBER_OF_ROBOTS = 10
TEAM_SIZE = 20
TEAM_START = 100
TEAM_END = TEAM_START + TEAM_SIZE
AUTO_BOT_SIZE = 5
COMM_TEAM_SIZE = TEAM_SIZE - AUTO_BOT_SIZE

# communication parameters
SUBNET_IP = '192.168.178.'
PORT = 5005 
SENDING_ATTEMPTS = 20
BC_IP = '192.168.178.255'

# protocol messages # TODO: define!
COMMAND_GO_IDLE = "GO_IDLE"
COMMAND_GO_AUTO = "GO_AUTO"
COMMAND_GO_COMM = "GO_COMM"
COMMAND_START_ALL = "START_ALL"
COMMAND_MODE = "mode"
COMMAND_SPEED = "speed"
COMMAND_BLINK = "blink"
VALUE_SPEED_INCREMENT = '+'
VALUE_SPEED_DECREMENT = '-'
VALUE_MODE_INIT = "init"
VALUE_MODE_IDLE = "idle"

# robots
DIST_MIN = 20
DIST_MAX = 50
DIST_REF = DIST_MAX

LED_OFF = 0
LED_ON = 1000

SPEED_RUN = 75
SPEED_WARN = round(float(SPEED_RUN)/3,0)
SPEED_STOP = 0

SPEED_MAX = 100
SPEED_MIN = 0
SPEED_CONTROL_MAX = SPEED_RUN-5
SPEED_CONTROL_MIN = SPEED_STOP

SENDING_ATTEMPTS = 5

TIME_TO_SLOW_DOWN = 3

WAIT_DIST = 0.1
WAIT_MOTOR = 0.05
WAIT_SEND = 0.00001
WAIT_SWITCH = 0.1






