# system variables
#NUMBER_OF_ROBOTS = 10
TEAM_SIZE = 20
TEAM_START = 100
TEAM_END = TEAM_START + TEAM_SIZE
AUTO_BOT_SIZE = 5
COM_TEAM_SIZE = TEAM_SIZE - AUTO_BOT_SIZE

# communication parameters
SUBNET_IP = '192.168.178.'
PORT = 5005 
SENDING_ATTEMPTS = 5
BC_IP = '192.168.178.255'

# protocol messages # TODO: define!
COMMAND_TYPE = "type"
VALUE_TYPE_COM = "go_com"
VALUE_TYPE_AUTO = "go_auto"
VALUE_TYPE_ORIGINAL = "go_original"
COMMAND_STATE = "state"
VALUE_STATE_RUNNING = "running"
VALUE_STATE_IDLE = "idle"
COMMAND_SPEED = "speed"
VALUE_SPEED_INCREMENT = '+'
VALUE_SPEED_DECREMENT = '-'
COMMAND_BLINK = "blink"
COMMAND_DIST = "dist"
COMMAND_RESET = "reset"

# robots
DIST_MIN = 20
DIST_MAX = 50
LED_OFF = 0
LED_ON = 1000
SPEED_RUN = 75
SPEED_STOP = 0
SPEED_LIMIT_MAX = 100
SPEED_LIMIT_MIN = 0
TIME_TO_SLOW_DOWN = 3
TIME_TO_SPEED_UP = 3
WAIT_DIST = 0.13
WAIT_MOTOR = 0.05
WAIT_SEND = 0.01
WAIT_SWITCH = 0.1
WAIT_LED = 0.35






