#!/bin/bash
# send files to all robots

IP_START=100
ROBOT_COUNT=15
IP_END=$(($IP_START+$ROBOT_COUNT))
echo "Transmitting all relevant files to Robots in IP-Range from 192.168.178.$IP_START to 192.168.178.$IP_END"
for ip_counter in $(seq $IP_START $IP_END)
do
	ping -c 1  192.168.178.$ip_counter -w1  2>/dev/null 1>/dev/null
	if [ "$?" = 0 ]
	then
		echo "Connection to 192.168.178.$ip_counter successfull!"
		scp robot.py pi@192.168.178.$ip_counter:./pi2go 
		scp constants.py pi@192.168.178.$ip_counter:./pi2go 
		scp communication.py pi@192.168.178.$ip_counter:./pi2go
		scp helper.py pi@192.168.178.$ip_counter:./pi2go
		scp pi2go.py pi@192.168.178.$ip_counter:./pi2go
		
	else
		echo "failed: 192.168.178.$ip_counter"
	fi
done
