
# system variables
#NUMBER_OF_ROBOTS = 10
SQUAD_SIZE = 20
SQUAD_START = 100
AUTO_BOT_SIZE = 5
COMM_SQUAD_SIZE = SQUAD_SIZE - AUTO_BOT_SIZE

# communication parameters
COMMAND_PORT = 5005
MODE_PORT= 5006 
PORT = 5005 # TODO: change name
SENDING_ATTEMPTS = 20
BC_IP = '192.168.178.255'

# protocol messages # TODO: define!
GO_IDLE = "GO_IDLE"
GO_AUTO = "GO_AUTO"
GO_COMM = "GO_COMM"
START_ALL = "START_ALL"

# robots
SPEED_RUN = 100
SPEED_SLOW = 80
SPEED_WARN = 25
SPEED_STOP = 0
SPEED_CONTROL_MAX = 75
SPEED_CONTROL_MIN = 50
DIST_MIN = 10
DIST_MAX = 50
DIST_REF = DIST_MAX
WAIT_DIST = 0.2
WAIT_SEND = 0.00001
LED_OFF = 0
LED_ON = 1000
SENDING_ATTEMPTS = 5
KP = 0.1



